# -*- coding: utf-8 -*-
"""Copy of DSA_00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEbZJv9qHz1vTmdYCKt8Ks_G7dIgO5Ut

1. Complete the following code to find the area of an equilateral triangle.Output should be as displayed
"""

import math
side = int(input("Enter the side of the equilateral triangle= "))
area = ((math.sqrt(3))/4) * pow(side, 2)
print(area)

"""2. Write a program to count the number of each characters in a string"""

string1 = input("Enter a string:")
list1 = []

for i in string1:
    if i in list1:
        continue
    else:
        print(i,string1.count(i))
        list1.append(i)

"""3.Write a program to find the area and perimeter of a rectangle using functions"""

def Rectangle():
  l=int(input("Length: "))
  w=int(input("Width: "))
  area=l*w
  perimeter=2*(l+w)
  print("Area of Rectangle : ",area)
  print("Perimeter of Rectangle: ",perimeter)

Rectangle()

"""4. Write a program to print the fibonacci series till a specified number"""

number = int(input('Enter a limit :'))
a, b = 0,1
if(number == a):
  print(a, end = " ")
else:
  print(a,b,end=" ")
while True:
    sum = a+b
    if(sum>number):
      break
    else:
      a, b = b, sum
      print(sum, end = " ")

"""
5. Complete the following code to find the minimum of 3 number using conditional statements. Output should be as displayed"""

a,b,c = input("Enter three numbers followed by space : ").split()
a = int(a) 
b = int(b)
c = int(c)
print("First number :",a)
print("Second number :",b)
print("Third number :",c)
if a==b==c:
    print("Entered numbers are equal!!!")
elif a<b and a<c:
    print(a," is smallest")
elif b<a and b<c:
    print(b," is smallest")
else:
    print(c," is smallest")

"""6. Write a program to print star pyramind. The number of rows should be taken as input from the user"""

def pyramid(n):
    k = n - 1
    for i in range(0, n):
        for j in range(0, k):
            print(end=" ")

        k = k - 1
        for j in range(0, i+1):
          print("* ", end="")
        print("\r")

n = int(input("Enter the number of raws in pyramid: "))
pyramid(n)

"""7. Complete the following code to convert hour into seconds. Output should be as displayed"""

def to_seconds(t):
  time_in_hours = t
  t = time_in_hours*60*60
  print(time_in_hours ," Hour is equal to" ,t ," Seconds")
t=int(input("Enter time in Hours :"))
to_seconds(t)

"""8. Write a program to print multiplication table as below"""

num = int(input("Enter a number to find the multiplication table:"))

for i in range(1,11):
    print(i,"x",num,"=",i*num)

"""9. Write a program to take your 5 favorite food as list and print each as 'I like Biriyani'"""

food=[]
food=input("Enter favorite food list followed by space :").split()
for i in food:
    print("I like ", i)

"""10. Find error(s) in the following code(if any) and rewrite code."""

x=int(input("Enter value of x:"))
for y in range(0,10):
     if x==y:
        print("They are equal")
     else:
        print( "They are unequal")